### PR TITLE
✨ react native support

### PR DESCRIPTION
**Pull request by mayteio**
- have migrated from react-scripts to jest, need to get `jest.rn.config.js` working.

### CODE REVIEW

**Comment by hsavit1** [comment]
how is this going? is there anything that you're stuck on in particular that you need help with?

**Comment by mayteio** [comment]
Hey @hsavit1, I haven’t made any progress on this. I can look at it this week, or accepting pull requests 🙏

**Comment by mayteio** [comment]
Hey @hsavit1 do you have capacity to work on this? I am snowed under with work at the moment. 

I think a mild restructure is required. We'd need to move things into a `src/web`, `src/react-native` structure then update rollup to generate multiple bundles - web @ root and rn at `@harelpls/use-pusher/react-native`. I personally haven't done this before, though am keen to learn. Do you know any resources for this?

**Comment by hsavit1** [comment]
can't say I've ever done anything like that before. I've never built a published custom hook before. I'll definitely stick my neck out there though and let you know what I find!

**Comment by mayteio** [comment]
resolves #5

**Pull request merged**
