### PR TITLE
Move dev deps out

### PR DESCRIPTION
**Pull request by cowsrule**
- Fix issue with `yarn test` command.
- Move deps (`jest`, `netinfo`) to `devDependencies` as they do not need to be required for production use
- Remove unused `devDependencies`

Am running into issues pulling this lib into a codebase with conflicting types. These changes minimize the number of deps consumers of this lib need to pull down and limits the potential react type conflicts.

This is a followup to https://github.com/mayteio/use-pusher/issues/16 which has otherwise been resolved. Appreciate your work creating this lib!

### CODE REVIEW

**Comment by cowsrule** [comment]
Hey @mayteio, is this type of PR something you're willing to take? The current deps essentially block as-is consumption of this lib in a number of cases.

**Comment by nikolaik** [comment]
> (...) The current deps essentially block as-is consumption of this lib in a number of cases.

+1 Would love to see this released

**Comment by mayteio** [comment]
Does this need a re-release to solve your issues @cowsrule @nikolaik ?

**Comment by cowsrule** [comment]
Yes, would need to pull in an updated package version.

**Comment by mayteio** [comment]
No problem - I am getting a few errors when trying to run tests though:

Screen Shot 2021-03-02 at 10 23 11 am

If you can fix these up I'll release it as soon as they pass.

**Comment by cowsrule** [comment]
Works great, thanks again!

**Pull request merged**
